// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _single_block_AES_encrypt_HH_
#define _single_block_AES_encrypt_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "single_block_AES_encrypt_aes_cipher.h"
#include "single_block_AES_encrypt_aes_key_expansion.h"
#include "single_block_AES_encrypt_plaintext.h"
#include "single_block_AES_encrypt_w.h"

namespace ap_rtl {

struct single_block_AES_encrypt : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<8> > i_plaintext_TDATA;
    sc_in< sc_logic > i_plaintext_TVALID;
    sc_out< sc_logic > i_plaintext_TREADY;
    sc_in< sc_lv<1> > i_plaintext_TUSER;
    sc_in< sc_lv<1> > i_plaintext_TLAST;
    sc_out< sc_lv<8> > cipher_TDATA;
    sc_out< sc_logic > cipher_TVALID;
    sc_in< sc_logic > cipher_TREADY;
    sc_out< sc_lv<1> > cipher_TUSER;
    sc_out< sc_lv<1> > cipher_TLAST;


    // Module declarations
    single_block_AES_encrypt(sc_module_name name);
    SC_HAS_PROCESS(single_block_AES_encrypt);

    ~single_block_AES_encrypt();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    single_block_AES_encrypt_plaintext* plaintext_U;
    single_block_AES_encrypt_plaintext* out_U;
    single_block_AES_encrypt_w* w_U;
    single_block_AES_encrypt_aes_cipher* grp_single_block_AES_encrypt_aes_cipher_fu_141;
    single_block_AES_encrypt_aes_key_expansion* grp_single_block_AES_encrypt_aes_key_expansion_fu_150;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > i_plaintext_TDATA_blk_n;
    sc_signal< sc_lv<7> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_34;
    sc_signal< sc_lv<1> > exitcond1_fu_161_p2;
    sc_signal< sc_logic > cipher_TDATA_blk_n;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_46;
    sc_signal< sc_lv<5> > i_2_fu_167_p2;
    sc_signal< bool > ap_sig_52;
    sc_signal< sc_lv<5> > i_3_fu_189_p2;
    sc_signal< sc_lv<5> > i_3_reg_217;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_62;
    sc_signal< sc_lv<1> > exitcond_fu_183_p2;
    sc_signal< sc_lv<1> > tmp_last_V_fu_200_p2;
    sc_signal< sc_lv<1> > tmp_last_V_reg_227;
    sc_signal< sc_lv<4> > plaintext_address0;
    sc_signal< sc_logic > plaintext_ce0;
    sc_signal< sc_logic > plaintext_we0;
    sc_signal< sc_lv<8> > plaintext_q0;
    sc_signal< sc_lv<4> > out_address0;
    sc_signal< sc_logic > out_ce0;
    sc_signal< sc_lv<8> > out_q0;
    sc_signal< sc_lv<8> > w_address0;
    sc_signal< sc_logic > w_ce0;
    sc_signal< sc_lv<8> > w_q0;
    sc_signal< sc_lv<8> > w_address1;
    sc_signal< sc_logic > w_ce1;
    sc_signal< sc_lv<8> > w_q1;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_cipher_fu_141_ap_start;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_cipher_fu_141_ap_done;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_cipher_fu_141_ap_idle;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_cipher_fu_141_ap_ready;
    sc_signal< sc_lv<4> > grp_single_block_AES_encrypt_aes_cipher_fu_141_in_r_address0;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_cipher_fu_141_in_r_ce0;
    sc_signal< sc_lv<4> > grp_single_block_AES_encrypt_aes_cipher_fu_141_out_r_address0;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_cipher_fu_141_out_r_ce0;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_cipher_fu_141_out_r_we0;
    sc_signal< sc_lv<8> > grp_single_block_AES_encrypt_aes_cipher_fu_141_out_r_d0;
    sc_signal< sc_lv<8> > grp_single_block_AES_encrypt_aes_cipher_fu_141_w_address0;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_cipher_fu_141_w_ce0;
    sc_signal< sc_lv<8> > grp_single_block_AES_encrypt_aes_cipher_fu_141_w_address1;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_cipher_fu_141_w_ce1;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_ap_start;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_ap_done;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_ap_idle;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_ap_ready;
    sc_signal< sc_lv<8> > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_w_address0;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_w_ce0;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_w_we0;
    sc_signal< sc_lv<8> > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_w_d0;
    sc_signal< sc_lv<8> > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_w_address1;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_w_ce1;
    sc_signal< sc_logic > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_w_we1;
    sc_signal< sc_lv<8> > grp_single_block_AES_encrypt_aes_key_expansion_fu_150_w_d1;
    sc_signal< sc_lv<5> > i_reg_119;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_148;
    sc_signal< sc_lv<5> > i_1_reg_130;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_158;
    sc_signal< sc_logic > ap_sig_ioackin_cipher_TREADY;
    sc_signal< sc_logic > ap_reg_grp_single_block_AES_encrypt_aes_cipher_fu_141_ap_start;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_174;
    sc_signal< sc_logic > ap_reg_grp_single_block_AES_encrypt_aes_key_expansion_fu_150_ap_start;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_193;
    sc_signal< sc_lv<64> > tmp_fu_178_p1;
    sc_signal< sc_lv<64> > tmp_s_fu_195_p1;
    sc_signal< sc_logic > ap_reg_ioackin_cipher_TREADY;
    sc_signal< sc_lv<7> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<7> ap_ST_st1_fsm_0;
    static const sc_lv<7> ap_ST_st2_fsm_1;
    static const sc_lv<7> ap_ST_st3_fsm_2;
    static const sc_lv<7> ap_ST_st4_fsm_3;
    static const sc_lv<7> ap_ST_st5_fsm_4;
    static const sc_lv<7> ap_ST_st6_fsm_5;
    static const sc_lv<7> ap_ST_st7_fsm_6;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<5> ap_const_lv5_F;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_148();
    void thread_ap_sig_158();
    void thread_ap_sig_174();
    void thread_ap_sig_193();
    void thread_ap_sig_34();
    void thread_ap_sig_46();
    void thread_ap_sig_52();
    void thread_ap_sig_62();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_ioackin_cipher_TREADY();
    void thread_cipher_TDATA();
    void thread_cipher_TDATA_blk_n();
    void thread_cipher_TLAST();
    void thread_cipher_TUSER();
    void thread_cipher_TVALID();
    void thread_exitcond1_fu_161_p2();
    void thread_exitcond_fu_183_p2();
    void thread_grp_single_block_AES_encrypt_aes_cipher_fu_141_ap_start();
    void thread_grp_single_block_AES_encrypt_aes_key_expansion_fu_150_ap_start();
    void thread_i_2_fu_167_p2();
    void thread_i_3_fu_189_p2();
    void thread_i_plaintext_TDATA_blk_n();
    void thread_i_plaintext_TREADY();
    void thread_out_address0();
    void thread_out_ce0();
    void thread_plaintext_address0();
    void thread_plaintext_ce0();
    void thread_plaintext_we0();
    void thread_tmp_fu_178_p1();
    void thread_tmp_last_V_fu_200_p2();
    void thread_tmp_s_fu_195_p1();
    void thread_w_address0();
    void thread_w_address1();
    void thread_w_ce0();
    void thread_w_ce1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
